# Generated by Django 5.2.15 on 2026-06-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField()),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Lead (contacto)',
                'verbose_name_plural': 'Leads (contactos)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('summary', models.CharField(blank=True, max_length=240)),
                ('stack', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('summary', models.CharField(blank=True, max_length=240)),
                ('content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ICGS', max_length=120)),
                ('meta_description', models.CharField(blank=True, default='Servicios tecnológicos, automatización e infraestructura.', max_length=200)),
                ('hero_title', models.CharField(blank=True, default='Infraestructura y automatización para tu negocio', max_length=160)),
                ('hero_subtitle', models.TextField(blank=True, default='Diseño y despliego soluciones estables con Docker, Cloudflare y desarrollo Django/Odoo.')),
                ('primary_cta_text', models.CharField(blank=True, default='Solicitar propuesta', max_length=80)),
                ('primary_cta_url', models.CharField(blank=True, default='/contacto/', max_length=200)),
                ('secondary_cta_text', models.CharField(blank=True, default='Ver servicios', max_length=80)),
                ('secondary_cta_url', models.CharField(blank=True, default='/servicios/', max_length=200)),
                ('email', models.EmailField(blank=True, default='ivan@icgs.es', max_length=254)),
                ('footer_text', models.CharField(blank=True, default='Infraestructura, automatización y desarrollo para empresas.', max_length=200)),
                ('about_text', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ajustes del sitio',
                'verbose_name_plural': 'Ajustes del sitio',
            },
        ),
    ]
