# Generated by Django 5.2.15 on 2026-06-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('portal_intasa', 'Portal INTASA'), ('ordix', 'ORDIX CORE'), ('robotics', 'Robotics Lab')], default='portal_intasa', max_length=40)),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Captura de pantalla',
                'verbose_name_plural': 'Capturas de pantalla',
                'ordering': ['page', 'order'],
            },
        ),
    ]
