# Generated by Django 5.2.15 on 2026-06-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion_home', models.TextField(blank=True)),
                ('imagen_home', models.ImageField(blank=True, null=True, upload_to='soluciones/')),
                ('pie_imagen', models.CharField(blank=True, max_length=120)),
                ('url_detalle', models.CharField(max_length=200)),
                ('texto_cta', models.CharField(default='Ver solución →', max_length=80)),
                ('destacado_en_home', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Solución',
                'verbose_name_plural': 'Soluciones',
                'ordering': ['order'],
            },
        ),
    ]
