# Generated by Django 5.2.15 on 2026-06-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_solucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solucion',
            name='badge_clase',
            field=models.CharField(default='badge-dev', help_text='badge-live o badge-dev', max_length=30),
        ),
        migrations.AddField(
            model_name='solucion',
            name='badge_texto',
            field=models.CharField(blank=True, help_text="Texto del badge, ej: 'En producción'", max_length=60),
        ),
        migrations.AddField(
            model_name='solucion',
            name='cat',
            field=models.CharField(blank=True, help_text="Etiqueta sol-cat, ej: 'Inmobiliario · Oportunidades'", max_length=120),
        ),
        migrations.AddField(
            model_name='solucion',
            name='descripcion_card',
            field=models.TextField(blank=True, help_text='Descripción corta para la tarjeta'),
        ),
        migrations.AddField(
            model_name='solucion',
            name='icono_static',
            field=models.CharField(blank=True, help_text='Ruta relativa a static/, ej: img/icgs/ordix-mark.png', max_length=100),
        ),
        migrations.AddField(
            model_name='solucion',
            name='titulo_card',
            field=models.CharField(blank=True, help_text='Titular descriptivo del sol-card', max_length=200),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='descripcion_home',
            field=models.TextField(blank=True, help_text="Texto largo para la sección 'Caso real' de la home"),
        ),
    ]
