# Generated by Django 5.2.15 on 2026-06-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_solucion_badge_clase_solucion_badge_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='badge_clase',
            field=models.CharField(default='badge-dev', help_text='badge-live o badge-dev', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='badge_texto',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='cat',
            field=models.CharField(blank=True, help_text="Etiqueta sol-cat, ej: 'ICGS ROBOTICS LAB · Nexo Operativo'", max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='titulo_card',
            field=models.CharField(blank=True, help_text='Titular descriptivo del card', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='url_detalle',
            field=models.CharField(blank=True, help_text='URL de la página de detalle, ej: /proyectos/robotics-lab/', max_length=200),
        ),
    ]
