# Generated by Django 5.2.15 on 2026-06-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_badge_clase_project_badge_texto_project_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cta_texto',
            field=models.CharField(blank=True, default='Consultar →', max_length=80),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_url',
            field=models.CharField(blank=True, default='/contacto/', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Párrafo principal de presentación del servicio'),
        ),
        migrations.AddField(
            model_name='service',
            name='icono_key',
            field=models.CharField(blank=True, help_text='shield | server | code | gear', max_length=30),
        ),
        migrations.AddField(
            model_name='service',
            name='incluye',
            field=models.TextField(blank=True, help_text='Lista de lo que incluye — un elemento por línea'),
        ),
        migrations.AddField(
            model_name='service',
            name='precio_badge',
            field=models.CharField(blank=True, help_text='Ej: Desde 60 €/mes', max_length=60),
        ),
        migrations.AddField(
            model_name='service',
            name='precio_detalle',
            field=models.TextField(blank=True, help_text='Desglose de precios — una línea por tramo'),
        ),
    ]
